# Generated by Django 3.2.5 on 2021-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('hanqout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanqout',
            name='categories',
            field=models.ManyToManyField(related_name='hanqouts', to='categories.Category'),
        ),
    ]
