# Generated by Django 3.2.5 on 2021-07-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanqout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanqout',
            name='day',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hanqout',
            name='month',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='hanqout',
            name='year',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='hanqout',
            name='venue',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
