# Generated by Django 3.2.5 on 2021-07-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('hanqout', '0002_hanqout_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanqout',
            name='locations',
            field=models.ManyToManyField(related_name='hanqouts', to='locations.Location'),
        ),
    ]
