# Generated by Django 3.2.5 on 2021-07-23 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hanqout', '0003_hanqout_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanqout',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hanqouts', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
